name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # To get all tags for checking existing tags

      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Check for existing tag in PR
        if: github.event_name == 'pull_request'
        run: |
          VERSION=$(cat VERSION)
          if git rev-parse "v$VERSION" >/dev/null 2>&1; then
            echo "Tag v$VERSION already exists. This version has already been released or is planned for release. Please increment the version in the VERSION file."
            exit 1
          fi

      - run: go test ./...

  tag_and_release:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
<<<<<<< Updated upstream
=======
    permissions:
      contents: write
>>>>>>> Stashed changes
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # To get all tags

      - name: Create and push tag
        run: |
          VERSION=$(cat VERSION)
          git tag "v$VERSION"
          git push origin "v$VERSION"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
